
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gateway
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
  - port: {{ .Values.gateway.service.port }}
    targetPort: {{ .Values.gateway.service.targetPort }}
    protocol: TCP
  selector:
    app: gateway
