apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-orders
spec:
  type: {{ .Values.orders.service.type }}
  ports:
  - port: {{ .Values.orders.service.port }}
    targetPort: {{ .Values.orders.service.targetPort }}
    protocol: TCP
  selector:
    app: orders

